/**
 * AUTOGENERATED
 * @file assembler_test.cpp
 * @date 04.08.2023 22:25:41
 * @brief Тестирование записи инструкций в объектный файл
 */
#include "stdafx.h"
#include "assembler_test.h"
#include "assembler.h"

using namespace escript;
using namespace std;

void Assembler_Test::run()
{
    initTestCase();
    test_byteSequence();
    cleanupTestCase();
}

void Assembler_Test::initTestCase()
{

}

void Assembler_Test::cleanupTestCase()
{

}

void Assembler_Test::test_byteSequence()
{
    // проверяется корректность записи в память, никаких вычислений

    // буфер - объектный файл
    std::vector<uint8_t> obj;
    Assembler a(obj);
    // переменные для теста записи
    uint64_t uint64_t_value = 0;
    int64_t int64_t_value = 0;
    double double_value = 0;
    //uint64_t value32 = 0;
    //uint64_t value16 = 0;
    //uint64_t value8 = 0;

    // указатели для чтения
    uint8_t *p = nullptr;
    // сдвиг от начала буфера - счётчик, т.к. указательнельзя двигать просто так
    // т.к. буфер может перевыделяться, поэтому для доступа к буферу нужно
    // присвоить указатель "p" после выполнения команды
    size_t n = 0;


    a.nop();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::NOP);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::NOP);
    assert(obj.size() == n);
    
    a.halt();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::HALT);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::HALT);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.mov_a_data64(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::MOV_A_DATA64);
    assert(*p == (Assembler::OpCodeType)OpCode::MOV_A_DATA64);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.mov_b_data64(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::MOV_B_DATA64);
    assert(*p == (Assembler::OpCodeType)OpCode::MOV_B_DATA64);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.ld64_a_m(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::LD64_A_M);
    assert(*p == (Assembler::OpCodeType)OpCode::LD64_A_M);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.st64_m_a(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::ST64_M_A);
    assert(*p == (Assembler::OpCodeType)OpCode::ST64_M_A);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    a.adi_a_b();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::ADI_A_B);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::ADI_A_B);
    assert(obj.size() == n);
    
    a.imul_a_b();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::IMUL_A_B);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::IMUL_A_B);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.ldc_uint64_data64(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::LDC_UINT64_DATA64);
    assert(*p == (Assembler::OpCodeType)OpCode::LDC_UINT64_DATA64);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    int64_t_value = rand();
    a.ldc_int64_data64(int64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::LDC_INT64_DATA64);
    assert(*p == (Assembler::OpCodeType)OpCode::LDC_INT64_DATA64);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((int64_t *)p) == int64_t_value);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.ldloc_m(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::LDLOC_M);
    assert(*p == (Assembler::OpCodeType)OpCode::LDLOC_M);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    double_value = rand();
    a.ldc_double_data64(double_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::LDC_DOUBLE_DATA64);
    assert(*p == (Assembler::OpCodeType)OpCode::LDC_DOUBLE_DATA64);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((double *)p) == double_value);
    assert(obj.size() == n);
    
    a.addst();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::ADDST);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::ADDST);
    assert(obj.size() == n);
    
    a.mulst();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::MULST);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::MULST);
    assert(obj.size() == n);
    
    a.divst();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::DIVST);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::DIVST);
    assert(obj.size() == n);
    
    a.subst();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::SUBST);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::SUBST);
    assert(obj.size() == n);
    
    a.pop_a();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::POP_A);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::POP_A);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.cmp_a_d64(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::CMP_A_D64);
    assert(*p == (Assembler::OpCodeType)OpCode::CMP_A_D64);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    uint64_t_value = rand();
    a.stloc_m(uint64_t_value);
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::STLOC_M);
    assert(*p == (Assembler::OpCodeType)OpCode::STLOC_M);
    p += Assembler::INSTRUCTION_CODE_SIZE;
    assert(*((uint64_t *)p) == uint64_t_value);
    assert(obj.size() == n);
    
    a.neg();
    p = obj.data() + n;
    n += Assembler::instructionSize(OpCode::NEG);
    assert(*((Assembler::OpCodeType *)p) == (Assembler::OpCodeType)OpCode::NEG);
    assert(obj.size() == n);
    
}
