/**
 * AUTOGENERATED
 * @file opcode.h
 * @date $(Date)
 * @brief Перечисление кодов операций
 */
#ifndef OPCODE_H
#define OPCODE_H

namespace escript {

using OpCodeType = $(OpCodeEnumDataType);

/**
 * @brief Перечисление кодов операций
 */
enum class OpCode : $(OpCodeEnumDataType)
{
$(Enum)
};

} // namespace escript

#endif // OPCODE_H
